const initialSongs = [
    {
        id: 1,
        title:"Cute dog with an apple",
        artist: "HoangTrang",
        album: "Album 1",
        cover: "assets/covers/1.jpg",
        src: "assets/music/1.ogg",
        isPremium: false,
        views: 0,
        country: "vn",
        genre: "pop",
    },
    {
        id: 2,
        title:"Cute Clara Valac",
        artist: "Clara Valac",
        album: "Album 1",
        cover: "assets/covers/2.jpg",
        src: "assets/music/2.ogg",
        isPremium: true,
        views: 0,
        country: "usuk",
        genre: "pop",
    },
    {
        id: 3,
        title:"Mischievous Clara",
        artist: "Clara Valac",
        album: "Album 2",
        cover: "assets/covers/3.jpg",
        src: "assets/music/3.ogg",
        isPremium: false,
        views: 0,
        country: "vn",
        genre: "rock",
    },
    {
        id: 4,
        title:"Mc Dognal",
        artist: "Moi",
        album: "Album 3",
        cover: "assets/covers/4.jpg",
        src: "assets/music/4.ogg",
        isPremium: true,
        views: 0,
        country: "usuk",
        genre: "rock",
    },
    {
        id: 5,
        title:"Dog Gaming",
        artist: "HoangTrang",
        album: "Album 1",
        cover: "assets/covers/5.jpg",
        src: "assets/music/5.ogg",
        isPremium: false,
        views: 0,
        country: "vn",
        genre: "pop",
    },
    {
        id: 6,
        title:"Pattrick helo",
        artist: "Chihuahua",
        album: "Album 2",
        cover: "assets/covers/6.jpg",
        src: "assets/music/6.mp3",
        isPremium: false,
        views: 0,
        country: "vn",
        genre: "pop",
    },
    {
        id: 7,
        title:"Puppy huh",
        artist: "DogMoi",
        album: "Album 3",
        cover: "assets/covers/7.jpg",
        src: "assets/music/7.mp3",
        isPremium: false,
        views: 0,
        country: "usuk",
        genre: "rock",
    },
    {
        id: 8,
        title:"Duck hair",
        artist: "Vit Quack",
        album: "Album 1",
        cover: "assets/covers/8.jpg",
        src: "assets/music/8.mp3",
        isPremium: true,
        views: 0,
        country: "usuk",
        genre: "pop",
    },
    {
        id: 9,
        title:"Frieren odd",
        artist: "Himmel",
        album: "Album 5",
        cover: "assets/covers/9.jpg",
        src: "assets/music/9.mp3",
        isPremium: false,
        views: 0,
        country: "vn",
        genre: "rock",
    },
    {
        id: 10,
        title:"Happy girl",
        artist: "HoangTrang",
        album: "Album 4",
        cover: "assets/covers/10.jpg",
        src: "assets/music/10.mp3",
        isPremium: false,
        views: 0,
        country: "vn",
        genre: "pop",
    },
    {
        id: 11,
        title:"I'm a chill guy",
        artist: "Fire man",
        album: "Album 3",
        cover: "assets/covers/11.jpg",
        src: "assets/music/11.mp3",
        isPremium: false,
        views: 0,
        country: "vn",
        genre: "pop",
    },
    {
        id: 12,
        title:"Lao leo lizard",
        artist: "Green Thing",
        album: "Album 1",
        cover: "assets/covers/12.jpg",
        src: "assets/music/12.flac",
        isPremium: true,
        views: 0,
        country: "usuk",
        genre: "rock",
    },
    {
        id: 13,
        title:"Dancing Cat",
        artist: "Meow Master",
        album: "Album 2",
        cover: "assets/covers/1.jpg", 
        src: "assets/music/1.ogg",
        isPremium: false,
        views: 15,
        country: "usuk",
        genre: "pop",
    },
    {
        id: 14,
        title:"Sad Hamster",
        artist: "Moi",
        album: "Album 4",
        cover: "assets/covers/2.jpg",
        src: "assets/music/2.ogg",
        isPremium: true,
        views: 42,
        country: "vn",
        genre: "rock",
    },
    {
        id: 15,
        title:"Sleepy Bear",
        artist: "Gau Gau",
        album: "Album 1",
        cover: "assets/covers/3.jpg",
        src: "assets/music/3.ogg",
        isPremium: false,
        views: 8,
        country: "vn",
        genre: "pop",
    },
    {
        id: 16,
        title:"Crazy Frog",
        artist: "Froggy",
        album: "Album 5",
        cover: "assets/covers/4.jpg",
        src: "assets/music/4.ogg",
        isPremium: false,
        views: 99, 
        country: "usuk",
        genre: "rock",
    }
]

export default initialSongs;