const initialSongs = [
    {
        id: 1,
        title:"Cute dog with an apple",
        artist: "HoangTrang",
        album: "Album 1",
        cover: "assets/covers/1.jpg",
        src: "assets/music/1.ogg",
        isPremium: false,
        views: 0,
    },
    {
        id: 2,
        title:"Cute Clara Valac",
        artist: "Clara Valac",
        album: "Album 1",
        cover: "assets/covers/2.jpg",
        src: "assets/music/2.ogg",
        isPremium: true,
        views: 0,
    },
    {
        id: 3,
        title:"Mischievous Clara",
        artist: "Clara Valac",
        album: "Album 2",
        cover: "assets/covers/3.jpg",
        src: "assets/music/3.ogg",
        isPremium: false,
        views: 0,
    },
    {
        id: 4,
        title:"Mc Dognal",
        artist: "Moi",
        album: "Album 3",
        cover: "assets/covers/4.jpg",
        src: "assets/music/4.ogg",
        isPremium: true,
        views: 0,
    },
    {
        id: 5,
        title:"Dog Gaming",
        artist: "HoangTrang",
        album: "Album 1",
        cover: "assets/covers/5.jpg",
        src: "assets/music/5.ogg",
        isPremium: false,
        views: 0,
    },
]

export default initialSongs;